### ISSUE TITLE
'source' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by lovelyJason** [postmanlabs/postman-code-generators#647]
**Describe the bug**
执行`npm run package`时抛错
```
'source' is not recognized as an internal or external command, operable program or batch file.
    postman-code-generators\node_modules\shelljs\src\common.js:402
          if (config.fatal) throw e;
                            ^Error: exec: 'source' is not recognized as an internal or external command,
          operable program or batch file.
          
              at Object.error (D:\projects\postman-code-generators\node_modules\shelljs\src\common.js:111:27)
              at execSync (D:\projects\postman-code-generators\node_modules\shelljs\src\exec.js:120:12)
              at Object._exec (D:\projects\postman-code-generators\node_modules\shelljs\src\exec.js:223:12)
              at Object.exec (D:\projects\postman-code-generators\node_modules\shelljs\src\common.js:336:23)
              at Object.<anonymous> (D:\projects\postman-code-generators\npm\package.js:20:20)
              at Module._compile (internal/modules/cjs/loader.js:1015:30)
              at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
              at Module.load (internal/modules/cjs/loader.js:879:32)
              at Function.Module._load (internal/modules/cjs/loader.js:724:14)
              at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
For example you could add the screenshot of the snippet/request builder from Postman app.

**Additional context**
Version of postman-code-generators/Postman app: 8.12.2
Platform: windows10
nodejs version: v12.19.0

**Comment by kaifkh20** [comment]
any update on this issue?

**Comment by kaifkh20** [comment]
I think it's because of EOL issue.
If you change it to '\n' it might get fixed.
